name: luffy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  logger: ^1.1.0
  http: ^0.13.5
  get_storage: ^2.0.3
  path_provider: ^2.0.11
  json_annotation: ^4.7.0

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.5.4

flutter: 
  uses-material-design: true

