name: luffy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  path_provider: ^2.0.11
  json_annotation: ^4.7.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  summer: 
    path: ./pkg/summer
  flutter: 
    sdk: flutter
  flutter_webrtc: ^0.9.18
  web_socket_channel: ^2.2.0
  cached_network_image: ^3.2.3

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  json_serializable: ^6.5.4
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - .env.production
    - .env.development
  uses-material-design: true

